### ISSUE TITLE
HelloServer and AdvancedWebServer compilation error in v3.1.2

### ISSUE THREAD

**Issue by S10143806H** [menshen-tsai/Ameba_WebServer#1]
Hi @menshen-tsai,

Except for Ameba SDK built-in example `WiFiWebServer.ino`,  the other two examples provided in your repository are currently having compilation errors as shown below: 

### HelloServer.ino
![image](https://user-images.githubusercontent.com/9852678/174753017-aa6368d5-4c23-430d-9fd3-f620141117a2.png)

### AdvancedWebServer.ino
![image](https://user-images.githubusercontent.com/9852678/174753238-55bfcdd7-2e9e-402d-b382-358d475192d7.png)

Hope you could fix these incompatibles in the future. 

Or maybe you could write a clear example readme to guide the users as what Khoi Hoang did [here](https://github.com/khoih-prog/WiFiManager_RTL8720/blob/main/README.md).

Thank you.

**Comment by menshen-tsai** [comment]
For your first problem, LED_G and LED_B are two Macros defined in packages/realtek/hardware/AmebaD/3.1.2/variants/rtl8722dm_mini/variant.h. I dont have any problem using these two Macros.  I am not sure why you got the error messages.

For the second question, according to 
https://github.com/ambiot/ambd_arduino/issues/31, you need to remove the comment 
//#define Arduino_STD_PRINTF
in Arduino.h.
The file is in C:\Users\(yourusername)\AppData\Local\Arduino15/packages/realtek/hardware/AmebaD/3.1.2/cores/arduino/ if your are using Windows; or in home/user/.arduino15/packages/realtek/hardware/AmebaD/3.1.2/cores/arduino if you are using Ubuntu.



![image](https://user-images.githubusercontent.com/20353963/174814513-60663638-5c39-4df9-bcc5-3ed5ac1b9c95.png)
